config/routes.rb
Placman::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index', as: :authenticated_root
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :material_categories do
    resources :materials
  end

  

end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id                   :integer          not null, primary key
#  created_at           :datetime
#  updated_at           :datetime
#  denomination         :string(255)
#  unit                 :string(255)      default("Unit")
#  material_category_id :integer
#

class Material < ActiveRecord::Base
  validates :denomination, presence: true
  validates :unit, presence: true
  
  UNIT_OPTIONS = %w(Unit m&sup2;)
  validates :unit, :inclusion => {:in => UNIT_OPTIONS}
  
  belongs_to :material_category
end

app/models/material_category.rb
# == Schema Information
#
# Table name: material_categories
#
#  id                   :integer          not null, primary key
#  created_at           :datetime
#  updated_at           :datetime
#  name                 :string(255)
#  material_category_id :integer
#

class MaterialCategory < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :materials, dependent: :destroy
  
  belongs_to :material_category
  has_many :material_categories, dependent: :destroy
  
  def materialsEmpty?
    self.materials.empty?
  end
  
  def categoriesEmpty?
    self.material_categories.empty?
  end
  
  def rootCategory?
    self.material_category.nil?
  end
  
  def setParentCategory(cat)
    if self.rootCategory?
      self.material_category = cat
    else
      raise "Error: Category has already a parent category"
    end
  end
  
  def setParentCategory!(cat)
    self.setParentCategory(cat)
    self.save
  end
  
  def addMaterial(mat)
    if self.categoriesEmpty?
      self.materials.push(mat)
    else
      raise "Error: Category contains already subcategories"
    end
  end
  
  def addCategory(cat)
    if self.materialsEmpty?
      self.material_categories.push(cat)
    else
      raise "Error: Category contains already materials"
    end
  end
  
  def addMaterial!(mat)
    self.addMaterial(mat)
    self.save
  end
  
  def addCategory!(cat)
    self.addCategory(cat)
    self.save
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #unless :devise_controller?
    before_action :setMenu
  #end
  
  private
  
  def setMenu
    @homeMenu = true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:setMenu]
  
  def index
    @users = User.all
  end
  
  private
  
  def setMenu
    @homeMenu = true
  end
end

app/controllers/material_categories_controller.rb
class MaterialCategoriesController < ApplicationController
  before_filter :authenticate_user!
  skip_before_action :authenticate_user!, only: [:setMenu]
  
  def index
    @material_categories = Array.new
    MaterialCategory.all.each do |mc|
      if mc.rootCategory?
        @material_categories.push(mc)
      end
    end
  end
  
  def show
    @material_category = MaterialCategory.find(params[:id])
  end
  
  def new
    @material_category = MaterialCategory.new
    if !params[:parentCatId].nil?
      @parentCat = MaterialCategory.find(params[:parentCatId])
    end
  end
  
  def create
    if !params[:parentCatId].nil?
      @parentCat = MaterialCategory.find(params[:parentCatId])
    end
    
    @material_category = MaterialCategory.new(material_category_params)

    if ! @material_category.save
      flash.now[:error] = t('save_failed')
          
      render :template => "material_categories/new"  
    else

      if !@parentCat.nil? && !@parentCat.addCategory!(@material_category)
        flash.now[:error] = t('save_failed')
            
        render :template => "material_categories/new"
      else
        flash[:notice] = t('save_success')
        
        redirect_to @material_category
      end

    end
  end
  
  def edit
    @material_category = MaterialCategory.find(params[:id])
  end
  
  def update
    @material_category = MaterialCategory.find(params[:id])

    if ! @material_category.update(material_category_params)
      flash.now[:error] = t('save_failed')
          
      render :template => "material_categories/edit"  
    else
      flash[:notice] = t('edit_success')
      
      redirect_to @material_category
    end
  end
  
  def destroy
    @material_category = MaterialCategory.find(params[:id])
    @material_category.destroy
    
    # Détruire en cascade
    
    flash[:notice] = t('destroy_success')
    
    redirect_to material_categories_path
  end
  
  private
  
  def setMenu
    @material_categoriesMenu = true
  end
  
  def material_category_params
    params.require(:material_category).permit(:name, :parentCatId)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_filter :authenticate_user!
  skip_before_action :authenticate_user!, only: [:setMenu]
  
  def show
    @material = Material.find(params[:id])
  end
  
  def new
    @material = Material.new
    @parentCat = MaterialCategory.find(params[:material_category_id])
  end
  
  def create
    @parentCat = MaterialCategory.find(params[:material_category_id])
    
    @material = Material.new(material_params)

    if ! @material.save
      flash.now[:error] = t('save_failed')
          
      render :template => "materials/new"  
    else

      if !@parentCat.nil? && !@parentCat.addMaterial!(@material)
        flash.now[:error] = t('save_failed')
            
        render :template => "materials/new"
      else
        flash[:notice] = t('save_success')
        
        redirect_to material_category_path(@parentCat)
      end

    end
  end
  
  def edit
    @material = Material.find(params[:id])
  end
  
  def update
    @material = Material.find(params[:id])

    if ! @material.update(material_params)
      flash.now[:error] = t('save_failed')
          
      render :template => "materials/edit"  
    else
      flash[:notice] = t('edit_success')
      
      redirect_to material_category_path(@material.material_category)
    end
  end
  
  def destroy
    @material = Material.find(params[:id])
    parentCat = @material.material_category
    @material.destroy
    
    flash[:notice] = t('destroy_success')
    
    redirect_to material_category_path(parentCat)
  end
  
  private
  
  def setMenu
    @material_categoriesMenu = true
  end
  
  def material_params
    params.require(:material).permit(:denomination, :unit, :material_category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:setMenu]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def setMenu
    @usersMenu = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% content_for :title do %>Welcome<% end %>
<h2>Welcome...</h2>
<p>... on the home page!</p>
<h3>Users</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.email, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</button>
<a class="brand" href="#">Placman</a>
<div class="nav-collapse collapse">
	<ul class="nav">
		<li <% if @homeMenu %>class="active"<% end -%>><%= link_to t('Home'), root_path %></li>
		<li <% if @material_categoriesMenu %>class="active"<% end -%>><%= link_to t('Materials'), material_categories_path %></li>
	</ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Placman" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Placman" %>">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main">
	  <div class="container">
		    <header class="navbar navbar-inverse navbar-fixed-top">
		      <nav class="navbar-inner">
		        <div class="container">
		          <%= render 'layouts/navigation' %>
		        </div>
		      </nav>
		    </header>
	        <div class="content">
	           <div class="row">
	            <div class="span12">
	              <%= render 'layouts/messages' %>
	              <%= yield %>
	            </div>
	          </div>
	        </div>
	        <footer>
	          	&copy; Placman / <%= link_to 'Christian Brel', "http://www.christianbrel.fr" %>
	        </footer>
	  </div>
    </main>
  </body>
</html>

app/views/material_categories/_material_categories_list.html.erb
<table class="table table-striped">
	<thead>
	<tr>
	  <th>#</th>
	  <th><%= t('MaterialCategoryName') %></th>
	  <th><%= t('Subcategories') %> (sc) <%= t('Or') %> <%= t('Materials') %> (m)</th>
	</tr>
	</thead>
	<tbody>
		<% @material_categories.each do |mc| %>
		<tr>
			<td><%= mc.id %></td>
			<td><%= link_to mc.name, material_category_path(mc) %></td>
			<td>
				<% if !mc.categoriesEmpty? %>
					<ul>
						<% mc.material_categories.each do |smc| %>
							<li><%= link_to '(sc) ' + smc.name, material_category_path(smc) %></li>
						<% end %>
					</ul>
				<% else %>
					<% if !mc.materialsEmpty? %>
						<ul>
							<% mc.materials.each do |m| %>
								<li><%= link_to '(m) ' + m.denomination, material_category_material_path(m.material_category, m) %> ( <%= m.unit.html_safe %> )</li>
							<% end %>
						</ul>
					<% else %>
						<%= t('EmptyCategory') %>
					<% end %>
				<% end %>
			</td>
			<td>
				<%= link_to '<i class="icon-pencil icon-white"></i> '.html_safe, edit_material_category_path(mc), class: "btn btn-info btn-mini" %>
				<%= link_to '<i class="icon-remove icon-white"></i> '.html_safe, material_category_path(mc), method: :delete, data: { confirm: t('ConfirmDelete?') }, class: "btn btn-danger btn-mini" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/material_categories/_material_category_form.html.erb
	<div class="control-group<% if @material_category.errors[:name] and ! @material_category.errors[:name].empty? %> error<% end %>">
		<%= f.label :name, t('MaterialCategoryName') + " *", :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :name, :class => "input-large" %>
			<% if @material_category.errors[:name] and ! @material_category.errors[:name].empty? %>
				<span class="help-inline"><%= @material_category.errors[:name].join(', ') %></span>
			<% end %>
		</div>
	</div>

app/views/material_categories/_materials_list.html.erb
<table class="table table-striped">
	<thead>
	<tr>
	  <th>#</th>
	  <th><%= t('MaterialDenomination') %></th>
	  <th><%= t('MaterialUnit') %></th>
	</tr>
	</thead>
	<tbody>
		<% @materials.each do |m| %>
		<tr>
			<td><%= m.id %></td>
			<td><%= link_to m.denomination, material_category_material_path(m.material_category, m) %></td>
			<td><%= m.unit.html_safe %></td>
			<td>
				<%= link_to '<i class="icon-pencil icon-white"></i> '.html_safe, edit_material_category_material_path(m.material_category, m), class: "btn btn-info btn-mini" %>
				<%= link_to '<i class="icon-remove icon-white"></i> '.html_safe, material_category_material_path(m.material_category, m), method: :delete, data: { confirm: t('ConfirmDelete?') }, class: "btn btn-danger btn-mini" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/material_categories/edit.html.erb
<div class="row-fluid"> 
    <div class="page-header">
        <h1><%= t('MaterialCategory') %> <small><%= t('EditRecording') %></small></h1>
    </div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= form_for @material_category, url: {action: "update"}, html: {class: "form-horizontal"} do |f| %>
		  <%= render :partial => "material_category_form", :locals => { :f => f }  %>
		  <div class="control-group">
                <div class="controls">
                     <%= f.submit t('EditMaterialCategory'), :class => "btn btn-primary" %>
                </div>
          </div>
		<% end %>
	</div>
</div>

app/views/material_categories/index.html.erb
<div>
  <%= link_to '<i class="icon-plus-sign icon-white"></i> '.html_safe + t("NewMaterialCategory"), new_material_category_path, class: "btn btn-primary" %>
</div>

<% if @material_categories.nil? %>
<div class="alert alert-info">
	<%= t('NoRecordedCategories') %>
</div>
<% else %>
	<%= render :partial => "material_categories_list", :locals => { :@material_categories => @material_categories }  %>
<% end %>

app/views/material_categories/new.html.erb
<div class="row-fluid"> 
    <div class="page-header">
        <h1><%= t('MaterialCategory') %> <small><%= t('NewRecording') %></small></h1>
    </div>
</div>

<div class="row-fluid">
	<div class="span12">
<% if !@parentCat.nil? %>
	<%= form_for([@parentCat, @parentCat.material_categories.build], url: {controller: "material_categories", action: "create", parentCatId: @parentCat.id}, html: {class: "form-horizontal"}) do |f| %>
	  <%= render :partial => "material_category_form", :locals => { :f => f } %>
	  <div class="control-group">
	        <div class="controls">
	             <%= f.submit t('SaveMaterialCategory'), :class => "btn btn-primary" %>
	        </div>
	  </div>
	<% end %>
<% else %>
	<%= form_for @material_category, url: {action: "create"}, html: {class: "form-horizontal"} do |f| %>
	  <%= render :partial => "material_category_form", :locals => { :f => f }  %>
	  <div class="control-group">
	        <div class="controls">
	             <%= f.submit t('SaveMaterialCategory'), :class => "btn btn-primary" %>
	        </div>
	  </div>
	<% end %>
<% end %>
	</div>
</div>

app/views/material_categories/show.html.erb
<h1><%= t('MaterialCategoryDetails') %></h1>

<h2>
	<%= t('MaterialCategoryName') %> : <%= @material_category.name %>
	<%= link_to '<i class="icon-pencil icon-white"></i> '.html_safe, edit_material_category_path(@material_category), class: "btn btn-info btn-mini" %>
	<%= link_to '<i class="icon-remove icon-white"></i> '.html_safe, material_category_path(@material_category), method: :delete, data: { confirm: t('ConfirmDelete?') }, class: "btn btn-danger btn-mini" %>
</h2>

<div class="alert">
	<% if @material_category.rootCategory? %>
		<%= t('HasNoParentCategory') %>
	<% else %>
		<%= t('ParentCategory') + ' : ' %><%= link_to @material_category.material_category.name, material_category_path(@material_category.material_category) %>
	<% end %>
</div>

<% if !@material_category.materialsEmpty? %>

<h3>
	<%= t('MaterialsList') %>
	<%= link_to '<i class="icon-plus-sign icon-white"></i> '.html_safe + t("AddMaterial"), new_material_category_material_path(@material_category), class: "btn btn-info" %>
</h3>

<%= render :partial => "materials_list", :locals => { :@materials => @material_category.materials }  %>


<% elsif !@material_category.categoriesEmpty? %>
<h3>
	<%= t('SubcategoriesList') %>
	<%= link_to '<i class="icon-plus-sign icon-white"></i> '.html_safe + t("AddSubcategory"), new_material_category_path(:parentCatId => @material_category.id), class: "btn btn-info" %>
</h3>

<%= render :partial => "material_categories_list", :locals => { :@material_categories => @material_category.material_categories }  %>

<% else %>
	<div class="alert alert">
		<%= t('EmptyMaterialCategory') %>
	</div>
	<%= link_to '<i class="icon-plus-sign icon-white"></i> '.html_safe + t("AddMaterial"), new_material_category_material_path(@material_category), class: "btn btn-info" %>
	<%= link_to '<i class="icon-plus-sign icon-white"></i> '.html_safe + t("AddSubcategory"), new_material_category_path(:parentCatId => @material_category.id), class: "btn btn-primary" %>
<% end %>

app/views/materials/_material_form.html.erb
	<div class="control-group<% if @material.errors[:denomination] and ! @material.errors[:denomination].empty? %> error<% end %>">
		<%= f.label :denomination, t('MaterialDenomination') + " *", :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :denomination, :class => "input-large" %>
			<% if @material.errors[:denomination] and ! @material.errors[:denomination].empty? %>
				<span class="help-inline"><%= @material.errors[:denomination].join(', ') %></span>
			<% end %>
		</div>
	</div>
	
	<div class="control-group<% if @material.errors[:unit] and ! @material.errors[:unit].empty? %> error<% end %>">
		<%= f.label :unit, t('MaterialUnit') + " *", :class => "control-label" %>
		<div class="controls">
			<%= f.select :unit, Material::UNIT_OPTIONS.map {|u| [u.html_safe,u]} %>
			<% if @material.errors[:unit] and ! @material.errors[:unit].empty? %>
				<span class="help-inline"><%= @material.errors[:unit].join(', ') %></span>
			<% end %>
		</div>
	</div>

app/views/materials/edit.html.erb
<div class="row-fluid"> 
    <div class="page-header">
        <h1><%= t('Material') %> <small><%= t('EditRecording') %></small></h1>
    </div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= form_for @material, url: {action: "update"}, html: {class: "form-horizontal"} do |f| %>
		  <%= render :partial => "material_form", :locals => { :f => f }  %>
		  <div class="control-group">
                <div class="controls">
                     <%= f.submit t('EditMaterial'), :class => "btn btn-primary" %>
                </div>
          </div>
		<% end %>
	</div>
</div>

app/views/materials/new.html.erb
<div class="row-fluid"> 
    <div class="page-header">
        <h1><%= t('Material') %> <small><%= t('NewRecording') %></small></h1>
    </div>
</div>

<div class="row-fluid">
	<div class="span12">
	<%= form_for([@parentCat, @parentCat.materials.build], url: {controller: "materials", action: "create", material_category_id: @parentCat.id}, html: {class: "form-horizontal"}) do |f| %>
	  <%= render :partial => "material_form", :locals => { :f => f } %>
	  <div class="control-group">
	        <div class="controls">
	             <%= f.submit t('SaveMaterial'), :class => "btn btn-primary" %>
	        </div>
	  </div>
	<% end %>
	</div>
</div>

app/views/materials/show.html.erb
<h1><%= t('MaterialDetails') %></h1>

<h2>
	<%= t('MaterialDenomination') %> : <%= @material.denomination %> ( <%= @material.unit.html_safe %> )
	<%= link_to '<i class="icon-pencil icon-white"></i> '.html_safe, edit_material_category_material_path(@material.material_category, @material), class: "btn btn-info btn-mini" %>
	<%= link_to '<i class="icon-remove icon-white"></i> '.html_safe, material_category_material_path(@material.material_category, @material), method: :delete, data: { confirm: t('ConfirmDelete?') }, class: "btn btn-danger btn-mini" %>
</h2>

<div class="alert">
	<%= t('ParentCategory') + ' : ' %><%= link_to @material.material_category.name, material_category_path(@material.material_category) %>
</div>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>